version: '2'

services:
  database:
    container_name: relayer-db
    image: mysql:8
    restart: always
    volumes:
      - $IOTEX_RELAYER/data/mysql:/var/lib/mysql:rw
    environment:
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  iotex-relayer:
    container_name: iotex-relayer
    image: relayer:latest
    restart: on-failure
    ports:
      - 7001:7001
      - 8001:8001
    volumes:
      - $IOTEX_RELAYER/etc/relayer-config-iotex.yaml:/etc/iotube-relayer/relayer-config-iotex.yaml:ro
    links:
      - database
    command: relayer -config=/etc/iotube-relayer/relayer-config-iotex.yaml

  ethereum-relayer:
    container_name: ethereum-relayer
    image: relayer:latest
    restart: on-failure
    ports:
      - 7000:7000
      - 8000:8000
    volumes:
      - $IOTEX_RELAYER/etc/relayer-config-ethereum.yaml:/etc/iotube-relayer/relayer-config-ethereum.yaml:ro
    links:
      - database
    command: relayer -config=/etc/iotube-relayer/relayer-config-ethereum.yaml

#  heco-relayer:
#    container_name: heco-relayer
#    image: relayer:latest
#    restart: on-failure
#    ports:
#      - 7002:7002
#      - 8002:8002
#    volumes:
#      - $IOTEX_RELAYER/etc/relayer-config-heco.yaml:/etc/iotube-relayer/relayer-config-heco.yaml:ro
#    links:
#      - database
#    command: relayer -config=/etc/iotube-relayer/relayer-config-heco.yaml

#  polis-relayer:
#    container_name: polis-relayer
#    image: relayer:latest
#    restart: on-failure
#    ports:
#      - 7005:7005
#      - 8005:8005
#    volumes:
#      - $IOTEX_RELAYER/etc/relayer-config-polis.yaml:/etc/iotube-relayer/relayer-config-polis.yaml:ro
#    links:
#      - database
#    command: relayer -config=/etc/iotube-relayer/relayer-config-polis.yaml

  bsc-relayer:
    container_name: bsc-relayer
    image: relayer:latest
    restart: on-failure
    ports:
      - 7003:7003
      - 8003:8003
    volumes:
      - $IOTEX_RELAYER/etc/relayer-config-bsc.yaml:/etc/iotube-relayer/relayer-config-bsc.yaml:ro
    links:
      - database
    command: relayer -config=/etc/iotube-relayer/relayer-config-bsc.yaml

  matic-relayer:
    container_name: matic-relayer
    image: relayer:latest
    restart: on-failure
    ports:
      - 7004:7004
      - 8004:8004
    volumes:
      - $IOTEX_RELAYER/etc/relayer-config-matic.yaml:/etc/iotube-relayer/relayer-config-matic.yaml:ro
    links:
      - database
    command: relayer -config=/etc/iotube-relayer/relayer-config-matic.yaml

  iotex-solana-relayer:
    container_name: iotex-solana-relayer
    image: relayer:latest
    restart: on-failure
    ports:
      - 7008:7008
      - 8008:8008
    volumes:
      - $IOTEX_RELAYER/etc/relayer-config-iotex-solana.yaml:/etc/iotube-relayer/relayer-config-iotex-solana.yaml:ro
    links:
      - database
    command: relayer -config=/etc/iotube-relayer/relayer-config-iotex-solana.yaml

  solana-relayer:
    container_name: solana-relayer
    image: relayer:latest
    restart: on-failure
    ports:
      - 7007:7007
      - 8007:8007
    volumes:
      - $IOTEX_RELAYER/etc/relayer-config-solana.yaml:/etc/iotube-relayer/relayer-config-solana.yaml:ro
    links:
      - database
    command: relayer -config=/etc/iotube-relayer/relayer-config-solana.yaml

  cron:
    image: schnitzler/mysqldump
    restart: always
    volumes:
      - $IOTEX_RELAYER/etc/crontab:/var/spool/cron/crontabs/root
      - $IOTEX_RELAYER/etc/backup:/usr/local/bin/backup
    volumes_from:
      - backup
    command: ["-l", "8", "-d", "8"]
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: relayer

  backup:
    image: busybox
    volumes:
      - $IOTEX_RELAYER/data/backup:/backup
