chain: "ethereum"
interval: 5m
clientURL: ""
ethConfirmBlockNumber: 20
ethGasPriceLimit: 10000000000
grpcPort: 7200
grpcProxyPort: 8200
privateKey: ""
slackWebHook: "" 
validators:
  - withPayload: true
    address: "0xE7eBA1CEA51EC9B3AcCC16728e3B8786560c59d5"
    cashiers:
      - "0x4Aad62e13cBd5cD6F5BcEc649cc24f6185011fe1"
database:
  uri: "root:kdfjjrU64fjK58H@tcp(database:3306)/relayer?parseTime=true"
  driver: "mysql"
transferTableName: "ethereum_transfers"
witnessTableName: "ethereum_witnesses"
